name: Bump Dev Version

on:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version
        id: bump_version
        run: |
          set -e
          version_file="ResInsightVersion.cmake"
          line=$(grep 'set(RESINSIGHT_DEV_VERSION' "$version_file")
          current_version_str_quoted=$(echo "$line" | sed -n 's/.*RESINSIGHT_DEV_VERSION \(.*\))/\1/p' | xargs)
          current_version_str=${current_version_str_quoted//"/}
          version_num_str=${current_version_str#.}.

          if ! [[ "$version_num_str" =~ ^[0-9]+$ ]]; then
            echo "Error: dev version is not a number: $version_num_str"
            exit 1
          fi

          new_version_num=$((10#$version_num_str + 1))
          new_version_num_str=$(printf "%02d" "$new_version_num")

          sed -i "s/\(set(RESINSIGHT_DEV_VERSION \"\).\)[0-9]\{1,\}\"/\1${new_version_num_str}/" "$version_file"
          
          new_version_str=".${new_version_num_str}"
          echo "new_dev_version=$new_version_str" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ResInsightVersion.cmake
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Bump RESINSIGHT_DEV_VERSION to ${{ steps.bump_version.outputs.new_dev_version }}"
          git push
