name: Spell Check

on:
  - push

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Spell check ApplicationExeCode
        uses: sobolevn/misspell-fixer-action@master
        with:
          options: "-rsvnuR ApplicationExeCode/"
      - name: Spell check ApplicationLibCode
        uses: sobolevn/misspell-fixer-action@master
        with:
          options: "-rsvnuR ApplicationLibCode/"
      - name: Spell check Fwk/AppFwk
        uses: sobolevn/misspell-fixer-action@master
        with:
          options: "-rsvnuR Fwk/AppFwk/"
      - name: Spell check GrpcInterface
        uses: sobolevn/misspell-fixer-action@master
        with:
          options: "-rsvnuR GrpcInterface/"
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Fixes by misspell-fixer"
          title: "Typos fix by misspell-fixer"
          branch: spell-check-patches
          branch-suffix: random
